### ISSUE TITLE
UniDep export method throws an error when column data elements are not of the same shape

### ISSUE THREAD

**Issue by edervishaj** [Jyonn/UnifiedTokenizer#1]
Hi,

I have been using your Legommenders framework recently. I am not sure if you are open to PRs, hence this issue.

I am trying to add new tokenized data as an additional column to an existing `UniDep`. After performing the union, I attempt to save the updated `UniDep` to disk but when I call the method `export`, `numpy` throws an error on line 360 saying that the data are not of the same shape. 

https://github.com/Jyonn/UnifiedTokenizer/blob/817b61304148aecdc477122a67e50255f0062e66/UniTok/unidep.py#L359-L361

Actually, `data[col_name]` is a list of lists so same shape is not guaranteed. Similar storing is performed by `UniTok`:

https://github.com/Jyonn/UnifiedTokenizer/blob/817b61304148aecdc477122a67e50255f0062e66/UniTok/unitok.py#L196-L198

By changing `UniDep` to behave like `UniTok`, it works fine.

**Comment by Jyonn** [comment]
Hi,

it is a great honor for me to have your issues that point out the bugs! Welcome to PRs and hope you and everyone can contribute to this fundamental project!
